name: ChatControlRed-MouBieCat
description: "該插件針對 ChatControlRed 擴充，提供更方便的使用方式。"

author: MouBieCat
website: https://github.com/moubiecat

version: ${project.version}
api-version: ${bukkit-api.version}
depend:
  - ChatControlRed

main: net.moubiecat.chatcontrol.MouBieCat

commands:
  MBChatControl:
    description: "主要的插件指令。"

permissions:
  MBChatControl.reload:
    description: "重載插件設定。"
    default: op
